name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'PPS C++/frontend/**'   # Usar comillas para espacios
  pull_request:
    paths:
      - 'PPS C++/frontend/**'   # Usar comillas para espacios

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './PPS C++/frontend'  # Escapar con comillas

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './PPS C++/frontend/package-lock.json'  # Especificar ruta
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm run test:ci
      
    - name: Build project
      run: npm run build
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: './PPS C++/frontend/coverage'  # Ruta completa
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './PPS C++/frontend/build'  # Ruta completa